### ISSUE TITLE
test: coverage upload crash outside GHA runners

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#1154]
**Describe the bug**

The post `test:all` coverage upload fails when executed outside of GHA runners. 

**To Reproduce**

(might need to also run `test:all` prior)

`npm run posttest:all`

**Expected behavior**

Does not crash. Does a graceful fallback to no-op (there's no need to upload coverage stats when the tests were ran locally)

Ideas for the fix:
1. Call codecov from a NodeJS script that decides at runtime if the coverage should be uploaded or not.
2. Take a look at the codecov documentation to see if maybe they already have some command line argument for achieving exactly what we need without having to write any code.

**Logs/Stack traces**

```sh
> posttest:all
> tap --no-check-coverage --coverage-report=lcov && codecov

  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.8.2
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration: 
    Endpoint: https://codecov.io
{
  commit: '6bede0f42c9204651122a91b4ae3c0f00d25bf97',
  branch: 'build-312',
  package: 'node-v3.8.2'
}
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /*******/cactus-origin -type f -name '*.gcno'  -exec gcov  {} +
    Failed to run gcov command.
==> Scanning for reports
    + /*******/cactus-origin/coverage/lcov.info
==> Uploading reports
/*******/cactus-origin/node_modules/teeny-request/build/src/agents.js:33
    const isHttp = uri.startsWith('http://');
                       ^

TypeError: Cannot read property 'startsWith' of undefined
    at Object.getAgent (/*******/cactus-origin/node_modules/teeny-request/build/src/agents.js:33:24)
    at requestToFetchOptions (/*******/cactus-origin/node_modules/teeny-request/build/src/index.js:65:30)
    at teenyRequest (/*******/cactus-origin/node_modules/teeny-request/build/src/index.js:121:30)
    at /*******/cactus-origin/node_modules/codecov/lib/codecov.js:214:9
    at /*******/cactus-origin/node_modules/teeny-request/build/src/index.js:219:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Screenshots**

`N/A`

**Cloud provider or hardware configuration:**

Development machine.

**Operating system name, version, build:**

```sh
$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 5.4.0-54-generic x86_64
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`v0.6.0`

**Hyperledger Cactus Plugins/Connectors Used**

N/A

**Additional context**

Low priority because it works on GHA, but still, it should not crash elsewhere either.

cc: @travis-payne

**Comment by petermetz** [comment]
Closing this for now because in the meantime we heavily refactored the test execution and at the moment we do not have coverage uploads working at all anyway.
