### ISSUE TITLE
ci: fix ci.sh script on Windows 10 Git Bash (MinGW64)

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#171]
**Describe the bug**

When I try to run `./tools/ci.sh` it fails.

**To Reproduce**

Clone the project
Open Git Bash on Windows 10 from the Start menu for example
Go to the project root and run

```sh
./tools/ci.sh
```

Wait for it....
crash.

**Expected behavior**

CI script should pass.

**Logs/Stack traces**

The CI script log:

```sh

***REDACTED*** MINGW64 ~/a/blockchain/blockchain-integration-framework (master)
$

***REDACTED*** MINGW64 ~/a/blockchain/blockchain-integration-framework (master)
$ ./tools/ci.sh
4.4.23(1)-release
++ command -v lscpu
+ '[' -x '' ']'
+ echo 'lscpu is not installed, skipping...'
lscpu is not installed, skipping...
++ command -v lsmem
+ '[' -x '' ']'
+ echo 'lsmem is not installed, skipping...'
lsmem is not installed, skipping...
++ command -v smem
+ '[' -x '' ']'
+ echo 'smem is not installed, skipping...'
smem is not installed, skipping...
+ '[' false = true ']'
+ docker --version
Docker version 19.03.8, build afacb8b
+ docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6
+ node --version
v12.18.0
+ npm --version
6.14.4
+ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0, JRE 11 Windows 10 amd64-64-Bit Compressed References 20200422_551 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - 838028fc9d based on jdk-11.0.7+10)
+ cd ***PATH_REDACTED***blockchain-integration-framework/tools/..
+ npm ci

> core-js@2.6.11 postinstall ***PATH_REDACTED***\blockchain-integration-framework\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall ***PATH_REDACTED***\blockchain-integration-framework\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> fsevents@1.2.11 install ***PATH_REDACTED***\blockchain-integration-framework\node_modules\watchpack\node_modules\fsevents
> node-gyp rebuild


***PATH_REDACTED***\blockchain-integration-framework\node_modules\watchpack\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2029, in GenerateOutput
    root_entries = _GatherSolutionFolders(
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1787, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1740, in _DictsToFolders
    for folder, contents in bucket.items():
AttributeError: 'MSVSProject' object has no attribute 'items'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ***PATH_REDACTED***\blockchain-integration-framework\node_modules\watchpack\node_modules\fsevents
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> secp256k1@4.0.0 install ***PATH_REDACTED***\blockchain-integration-framework\node_modules\secp256k1
> node-gyp-build || exit 0


> husky@4.2.5 install ***PATH_REDACTED***\blockchain-integration-framework\node_modules\husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@4.2.5 postinstall ***PATH_REDACTED***\blockchain-integration-framework\node_modules\husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

added 1364 packages in 48.811s
+ ./node_modules/.bin/lerna clean --yes
lerna notice cli v3.20.2
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-cmd-api-server\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-cockpit\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-common\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-core-api\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-plugin-keychain-memory\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-plugin-kv-storage-memory\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-plugin-ledger-connector-besu\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-plugin-ledger-connector-quorum\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-plugin-web-service-consortium\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-sdk\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-test-plugin-ledger-connector-quorum\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-test-plugin-web-service-consortium\node_modules
lerna info clean removing ***PATH_REDACTED***\blockchain-integration-framework\packages\cactus-test-tooling\node_modules
lerna success clean finished
+ ./node_modules/.bin/lerna bootstrap
lerna notice cli v3.20.2
lerna info Bootstrapping 13 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 13 packages
+ npm run build

> @hyperledger-labs/cactus@ build ***PATH_REDACTED***\blockchain-integration-framework
> npm-run-all build:dev build:prod


> @hyperledger-labs/cactus@ build:dev ***PATH_REDACTED***\blockchain-integration-framework
> npm-run-all build:dev:backend webpack:dev:web build:dev:frontend


> @hyperledger-labs/cactus@ build:dev:backend ***PATH_REDACTED***\blockchain-integration-framework
> npm-run-all lint clean generate-sdk tsc webpack:dev:node


> @hyperledger-labs/cactus@ lint ***PATH_REDACTED***\blockchain-integration-framework
> lerna exec --stream --ignore '*/*cockpit' -- cross-env DEBUG= tslint --project tsconfig.json

lerna notice cli v3.20.2
lerna notice filter excluding "*/*cockpit"
lerna info filter [ '!*/*cockpit' ]
lerna info Executing command in 12 packages: "cross-env DEBUG= tslint --project tsconfig.json"
lerna success exec Executed command in 12 packages: "cross-env DEBUG= tslint --project tsconfig.json"

> @hyperledger-labs/cactus@ clean ***PATH_REDACTED***\blockchain-integration-framework
> lerna exec --stream --ignore '*/*cockpit' -- del-cli dist/** && del-cli packages/cactus-sdk/src/main/typescript/generated/openapi/typescript-axios/*

lerna notice cli v3.20.2
lerna notice filter excluding "*/*cockpit"
lerna info filter [ '!*/*cockpit' ]
lerna info Executing command in 12 packages: "del-cli dist/**"
lerna success exec Executed command in 12 packages: "del-cli dist/**"

> @hyperledger-labs/cactus@ pregenerate-sdk ***PATH_REDACTED***\blockchain-integration-framework
> npm-run-all export-open-api-spec


> @hyperledger-labs/cactus@ export-open-api-spec ***PATH_REDACTED***\blockchain-integration-framework
> ts-node -e 'import("./packages/cactus-cmd-api-server/src/main/typescript/openapi-spec").then((x) => x.exportToFileSystemAsJson());'


***PATH_REDACTED***\blockchain-integration-framework\node_modules\typescript\lib\typescript.js:131064
                var error = new Error("Could not find source file: '" + fileName + "'.");
                            ^
Error: Could not find source file: '***PATH_REDACTED***/blockchain-integration-framework/=;''.
    at getValidSourceFile (***PATH_REDACTED***\blockchain-integration-framework\node_modules\typescript\lib\typescript.js:131064:29)
    at Object.getEmitOutput (***PATH_REDACTED***\blockchain-integration-framework\node_modules\typescript\lib\typescript.js:131447:30)
    at getOutput (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\index.ts:538:32)
    at Object.compile (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\index.ts:760:32)
    at _eval (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\bin.ts:321:22)
    at evalAndExit (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\bin.ts:296:14)
    at main (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\bin.ts:224:5)
    at Object.<anonymous> (***PATH_REDACTED***\blockchain-integration-framework\node_modules\ts-node\src\bin.ts:513:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/cactus@ export-open-api-spec: `ts-node -e 'import("./packages/cactus-cmd-api-server/src/main/typescript/openapi-spec").then((x) => x.exportToFileSystemAsJson());'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hyperledger-labs/cactus@ export-open-api-spec script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ***PATH_REDACTED***AppData\Roaming\npm-cache\_logs\2020-06-11T19_52_41_300Z-debug.log
ERROR: "export-open-api-spec" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/cactus@ pregenerate-sdk: `npm-run-all export-open-api-spec`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hyperledger-labs/cactus@ pregenerate-sdk script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ***PATH_REDACTED***AppData\Roaming\npm-cache\_logs\2020-06-11T19_52_41_340Z-debug.log
ERROR: "generate-sdk" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/cactus@ build:dev:backend: `npm-run-all lint clean generate-sdk tsc webpack:dev:node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hyperledger-labs/cactus@ build:dev:backend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ***PATH_REDACTED***AppData\Roaming\npm-cache\_logs\2020-06-11T19_52_41_371Z-debug.log
ERROR: "build:dev:backend" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/cactus@ build:dev: `npm-run-all build:dev:backend webpack:dev:web build:dev:frontend`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hyperledger-labs/cactus@ build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ***PATH_REDACTED***AppData\Roaming\npm-cache\_logs\2020-06-11T19_52_41_404Z-debug.log
ERROR: "build:dev" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger-labs/cactus@ build: `npm-run-all build:dev build:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @hyperledger-labs/cactus@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ***PATH_REDACTED***AppData\Roaming\npm-cache\_logs\2020-06-11T19_52_41_435Z-debug.log
2020-06-11T12:52:41-0700 [CI] FAILURE - runtime=315 seconds.

***REDACTED*** MINGW64 ~/a/blockchain/blockchain-integration-framework (master)
```

**Screenshots**

**Cloud provider or hardware configuration:**
Are you running the software on a dev machine or somewhere in the cloud?

**Operating system name, version, build:**

```sh
$ printf "$(uname -srm)\n$(cat /etc/os-release)\n"

cat: /etc/os-release: No such file or directory
MINGW64_NT-10.0-19041 3.1.4-340.x86_64 x86_64

```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

```sh
$ git rev-parse --short HEAD
54ab057
```

**Additional context**

The Windows 10 OS is a KVM QEMU guest.

**Comment by petermetz** [comment]
As of today, this is how it fails:

```sh
lerna-lite notice cli v1.17.0
lerna-lite info Executing command in 12 packages: "yarn run build:dev:backend:postbuild"
lerna-lite ERR! yarn run build:dev:backend:postbuild exited 1 in '@hyperledger/cactus-example-cbdc-bridging-backend'
lerna-lite ERR! yarn run build:dev:backend:postbuild stderr:
'cp' is not recognized as an internal or external command,
operable program or batch file.
command not found: cp
lerna-lite ERR! yarn run build:dev:backend:postbuild exited 1 in '@hyperledger/cactus-example-cbdc-bridging-backend'
lerna-lite WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
C:\Users\*****\a\cacti\node_modules\execa\lib\error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: yarn run build:dev:backend:postbuild
'cp' is not recognized as an internal or external command,
operable program or batch file.
command not found: cp
    at makeError (C:\Users\*****\a\cacti\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\*****\a\cacti\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (C:\Users\*****\a\cacti\node_modules\p-queue\dist\index.js:163:29) {
  shortMessage: 'Command failed with exit code 1: yarn run build:dev:backend:postbuild',
  command: 'yarn run build:dev:backend:postbuild',
  escapedCommand: 'yarn run "build:dev:backend:postbuild"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'cp' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n' +
    'command not found: cp',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pkg: Package {
    _id: '',
    licensePath: '',
    localDependencies: Map(0) {},
    name: '@hyperledger/cactus-example-cbdc-bridging-backend',
    [Symbol(location)]: 'C:\\Users\\*****\\a\\cacti\\examples\\cactus-example-cbdc-bridging-backend',
    [Symbol(resolved)]: Result {
      type: 'directory',
      registry: undefined,
      where: 'C:\\Users\\*****\\a\\cacti',
      raw: '@hyperledger/cactus-example-cbdc-bridging-backend@file:examples\\cactus-example-cbdc-bridging-backend',
      name: '@hyperledger/cactus-example-cbdc-bridging-backend',
      escapedName: '@hyperledger%2fcactus-example-cbdc-bridging-backend',
      scope: '@hyperledger',
      rawSpec: 'file:examples\\cactus-example-cbdc-bridging-backend',
      saveSpec: 'file:examples\\cactus-example-cbdc-bridging-backend',
      fetchSpec: 'C:\\Users\\*****\\a\\cacti\\examples\\cactus-example-cbdc-bridging-backend',
      gitRange: undefined,
      gitCommittish: undefined,
      gitSubdir: undefined,
      hosted: undefined
    },
    [Symbol(rootPath)]: 'C:\\Users\\*****\\a\\cacti',
    [Symbol(scripts)]: {
      solidity: 'hardhat compile',
      start: 'CONFIG_FILE=./example-config.json node dist/lib/main/typescript/cbdc-bridging-app-cli.js',
      watch: 'npm-watch',
      test: "nyc cucumber-js ./src/test/typescript/cucumber/features/*.feature --require-module ts-node/register --require './src/test/typescript/cucumber/*/*.ts'",
      webpack: 'npm-run-all webpack:dev',
      'webpack:dev': 'npm-run-all webpack:dev:node webpack:dev:web',
      'webpack:dev:node': 'webpack --env=dev --target=node --config ../../webpack.config.js',
      'webpack:dev:web': 'webpack --env=dev --target=web --config ../../webpack.config.js',
      'build:dev:backend:postbuild': 'mkdir -p ./dist/lib/fabric-contracts && cp -r ./src/fabric-contracts/* ./dist/lib/fabric-contracts/'
    }
  }
}
ERROR: "build:dev:backend:postbuild" exited with 1.
```
