### ISSUE TITLE
Supply Chain Example crashes in Docker

### ISSUE THREAD

**Issue by perryd01** [hyperledger/cacti#2073]
**Describe the bug**
during running the example docker container the app inside crahses and restarts over again

**To Reproduce**
follow [these steps](https://github.com/hyperledger/cactus#supply-chain-example):

**Expected behavior**
Cactus is reachable and its logged in terminal

**Logs/Stack traces**

```
2022-06-11 11:33:48,965 INFO exited: supply-chain-app (exit status 255; not expected)
2022-06-11 11:33:49,968 INFO spawned: 'supply-chain-app' with pid 12013
Keccak bindings are not compiled. Pure JS implementation will be used.
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
[2022-06-11T11:33:51.378Z] INFO (config-service): Configuration validation OK.
2022-06-11 11:33:51,379 INFO success: supply-chain-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-06-11T11:33:51.379Z] INFO (supply-chain-app): Instantiating new keychain plugin...
[2022-06-11T11:33:51.381Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=3b965306-c6b2-4ff5-92fc-1511f056030c
[2022-06-11T11:33:51.381Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
[2022-06-11T11:33:51.381Z] INFO (supply-chain-app): KeychainID='3b965306-c6b2-4ff5-92fc-1511f056030c'
[2022-06-11T11:33:51.384Z] INFO (SupplyChainAppDummyInfrastructure): Reusing the provided keychain plugin...
[2022-06-11T11:33:51.384Z] INFO (SupplyChainAppDummyInfrastructure): KeychainID='3b965306-c6b2-4ff5-92fc-1511f056030c'
[2022-06-11T11:33:51.384Z] DEBUG (supply-chain-app): Starting SupplyChainApp...
[2022-06-11T11:33:51.384Z] DEBUG (supply-chain-app): Registered signal handlers for graceful auto-shutdown
[2022-06-11T11:33:51.384Z] INFO (SupplyChainAppDummyInfrastructure): Starting dummy infrastructure...
2022-06-11 11:33:52,599 INFO reaped unknown pid 12246
[2022-06-11T11:33:52.600Z] ERROR (SupplyChainAppDummyInfrastructure): Starting of dummy infrastructure crashed:  Error: (HTTP code 500) server error - cgroups: cgroup mountpoint does not exist: unknown 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:324:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'server error',
  statusCode: 500,
  json: { message: 'cgroups: cgroup mountpoint does not exist: unknown' }
}
SupplyChainApp crashed. Existing... Error: (HTTP code 500) server error - cgroups: cgroup mountpoint does not exist: unknown 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:324:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'server error',
  statusCode: 500,
  json: { message: 'cgroups: cgroup mountpoint does not exist: unknown' }
}
2022-06-11 11:33:52,610 INFO exited: supply-chain-app (exit status 255; not expected)
2022-06-11 11:33:53,613 INFO spawned: 'supply-chain-app' with pid 12385
Keccak bindings are not compiled. Pure JS implementation will be used.
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
[2022-06-11T11:33:55.054Z] INFO (config-service): Configuration validation OK.
2022-06-11 11:33:55,054 INFO success: supply-chain-app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-06-11T11:33:55.055Z] INFO (supply-chain-app): Instantiating new keychain plugin...
[2022-06-11T11:33:55.057Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=d6d1e7ce-7ced-42bf-935d-de6a1e69473b
[2022-06-11T11:33:55.057Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
[2022-06-11T11:33:55.057Z] INFO (supply-chain-app): KeychainID='d6d1e7ce-7ced-42bf-935d-de6a1e69473b'
[2022-06-11T11:33:55.060Z] INFO (SupplyChainAppDummyInfrastructure): Reusing the provided keychain plugin...
[2022-06-11T11:33:55.060Z] INFO (SupplyChainAppDummyInfrastructure): KeychainID='d6d1e7ce-7ced-42bf-935d-de6a1e69473b'
[2022-06-11T11:33:55.060Z] DEBUG (supply-chain-app): Starting SupplyChainApp...
[2022-06-11T11:33:55.060Z] DEBUG (supply-chain-app): Registered signal handlers for graceful auto-shutdown
[2022-06-11T11:33:55.060Z] INFO (SupplyChainAppDummyInfrastructure): Starting dummy infrastructure...
2022-06-11 11:33:56,221 INFO reaped unknown pid 12625
[2022-06-11T11:33:56.222Z] ERROR (SupplyChainAppDummyInfrastructure): Starting of dummy infrastructure crashed:  Error: (HTTP code 500) server error - cgroups: cgroup mountpoint does not exist: unknown 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:324:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'server error',
  statusCode: 500,
  json: { message: 'cgroups: cgroup mountpoint does not exist: unknown' }
}
SupplyChainApp crashed. Existing... Error: (HTTP code 500) server error - cgroups: cgroup mountpoint does not exist: unknown 
    at /usr/src/app/node_modules/docker-modem/lib/modem.js:324:17
    at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  reason: 'server error',
  statusCode: 500,
  json: { message: 'cgroups: cgroup mountpoint does not exist: unknown' }
}
```

**Screenshots**
-
**Cloud provider or hardware configuration:**
locale machine

**Operating system name, version, build:**
- Manjaro Linux 21.2.6
- Docker version 20.10.16, build aa7e414fdc

```
Linux 5.15.41-1-MANJARO x86_64
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

**Hyperledger Cactus Plugins/Connectors Used**

**Additional context**

**Comment by AbhinavMir** [comment]
Could [this](https://github.com/docker/for-linux/issues/219#issuecomment-375160449) possibly be a solution? If only temporary. This seems to be a docker/kernel issue - but should be solvable.

**Comment by aruns05** [comment]
@perryd01  Is this sorted?

**Comment by outSH** [comment]
This looks like an issue in docker / Manjaro-docker package itself. Can you upgrade your OS / docker to latest available versions and retest?

**Comment by perryd01** [comment]
Tried it again, same error. I'm no longer working with this project so I don't have a chance to troubleshoot it more.
```
Docker version 24.0.7, build afdd53b4e3
Manjaro Linux 23.1.1
Kernel 6.1.69-1-MANJARO (64-bit)
```
