### ISSUE TITLE
build: fix release automation

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2175]
When I run the release automation to publish the packages to npm, it crashes
because some of the package.json files do not contain a `publishConfig` property.

```sh
$ yarn lerna publish from-git --loglevel=debug
lerna-lite verb publish @hyperledger/cactus-common
lerna-lite verb publish @hyperledger/cactus-plugin-ledger-connector-fabric-socketio
lerna-lite verb publish @hyperledger/cactus-plugin-ledger-connector-go-ethereum-socketio
lerna-lite verb publish @hyperledger/cactus-plugin-ledger-connector-sawtooth-socketio
lerna-lite sill HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/@hyperledger%2fcactus-plugin-ledger-connector-go-ethereum-socketio - Not found
lerna-lite sill     at /.../cactus/node_modules/npm-registry-fetch/lib/check-response.js:93:15
lerna-lite sill     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna-lite sill     at async publish (/.../cactus/node_modules/libnpmpublish/lib/publish.js:43:12)
lerna-lite sill     at async /.../cactus/node_modules/p-pipe/index.js:12:19
lerna-lite sill     at async run (/.../cactus/node_modules/p-queue/dist/index.js:163:29)
lerna-lite sill  HttpErrorGeneral: 404 Not Found - PUT https://registry.npmjs.org/@hyperledger%2fcactus-plugin-ledger-connector-go-ethereum-socketio - Not found
lerna-lite sill     at /.../cactus/node_modules/npm-registry-fetch/lib/check-response.js:93:15
lerna-lite sill     at processTicksAndRejections (node:internal/process/task_queues:96:5)
lerna-lite sill     at async publish (/.../cactus/node_modules/libnpmpublish/lib/publish.js:43:12)
lerna-lite sill     at async /.../cactus/node_modules/p-pipe/index.js:12:19
lerna-lite sill     at async run (/.../cactus/node_modules/p-queue/dist/index.js:163:29) {
lerna-lite sill   headers: [Object: null prototype] {
lerna-lite sill     date: [ 'Wed, 19 Oct 2022 05:03:32 GMT' ],
lerna-lite sill     'content-type': [ 'application/json' ],
lerna-lite sill     'content-length': [ '21' ],
lerna-lite sill     connection: [ 'keep-alive' ],
lerna-lite sill     'cf-ray': [ '75c6f7c07b1f97dc-SJC' ],
lerna-lite sill     vary: [ 'Accept-Encoding' ],
lerna-lite sill     server: [ 'cloudflare' ],
lerna-lite sill     'x-fetch-attempts': [ '1' ]
lerna-lite sill   },
lerna-lite sill   statusCode: 404,
lerna-lite sill   code: 'E404',
lerna-lite sill   method: 'PUT',
lerna-lite sill   uri: 'https://registry.npmjs.org/@hyperledger%2fcactus-plugin-ledger-connector-go-ethereum-socketio',
lerna-lite sill   body: { error: 'Not found' },
lerna-lite sill   pkgid: '@hyperledger/cactus-plugin-ledger-connector-go-ethereum-socketio@1.1.0'
lerna-lite sill }
lerna-lite ERR! E404 Not found
lerna-lite ERR! E404 Not found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by petermetz** [comment]
Re-opening until we can fix the release automation issues.

**Comment by petermetz** [comment]
The crash log from the latest execution of the auto-publishing workflow action: [2022-11-04-cacti-ci-release-automation-crash.log](https://github.com/hyperledger/cactus/files/9975579/2022-11-04-cacti-ci-release-automation-crash.log)
