### ISSUE TITLE
fix: cannot read config eslint-config-prettier/@typescript-eslint.js

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2306]
**Describe the bug**

There's a clash between the different ESLint configuration files used by the project root and the `./weaver/` sub-folder which is breaking the build because the ES lint running from the root package.json script is picking up (probably via globbing) the configuration file in the sub-directories.

**To Reproduce**

`yarn configure` on the main branch and then observe the crash of the linter script

**Expected behavior**

The main branch should always have the build passing just fine.

**Logs/Stack traces**

Full logs: 
[2023-02-27_hyperledger_cacti_yarn_configure_crash.log](https://github.com/hyperledger/cacti/files/10844701/2023-02-27_hyperledger_cacti_yarn_configure_crash.log)

```sh
$ eslint '*/*/src/**/*.{js,ts}' --quiet --fix && cspell "*/*/src/**/*.{js,ts}"

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Cannot read config file: /****/cacti//node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /****/cacti//weaver/core/drivers/fabric-driver/.eslintrc
    at Object.<anonymous> (/****/cacti//node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/****/cacti//node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at module.exports (/****/cacti//node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/****/cacti//node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/****/cacti//node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/****/cacti//node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "lint" exited with 2.
```

**Screenshots**

**Cloud provider or hardware configuration:**
Are you running the software on a dev machine or somewhere in the cloud?

**Operating system name, version, build:**

Ubuntu 20.04 (but it's also known to be broken in all other OS' as well)

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main`

**Hyperledger Cactus Plugins/Connectors Used**

N/A

**Additional context**

Should be just a matter of 
1. Explicitly telling the linter script in the root to use the root config only OR 
2. Specifically telling it to ignore the sub-folder's linter's configuration
3. Upgrade the linter version used within `./weaver/` (this might necessitate a lot of other changes to the source code in `./weaver/` itself and therefore the least likely to be an easy solution.  

Whichever is the easiest should be done.

**Comment by petermetz** [comment]
This was fixed by https://github.com/hyperledger/cacti/pull/2307
