### ISSUE TITLE
test(connector-iroha): fix flaky http 400 run-transaction-endpoint-v1.test.ts

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2343]
**Describe the bug**

Does not always happen. In fact it rarely happens. But when it does, it makes the test fail so we should look into fixing this somehow.

`./packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts`

```sh
2023-03-24T07:08:56.8051983Z 
2023-03-24T07:09:03.2751272Z Browserslist: caniuse-lite is outdated. Please run:
2023-03-24T07:09:03.2751864Z   npx browserslist@latest --update-db
2023-03-24T07:09:03.2752768Z   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
2023-03-24T07:09:08.5793671Z # Subtest: ./packages/cactus-plugin-ledger-connector-iroha/src/test/typescript/integration/run-transaction-endpoint-v1.test.ts
2023-03-24T07:09:08.5807130Z     # BEFORE runs tx on an Iroha v1.2.0 ledger
2023-03-24T07:09:08.5829230Z     ok 1 Pruning didn't throw OK
2023-03-24T07:09:16.9543366Z     # runs tx on an Iroha v1.2.0 ledger
2023-03-24T07:09:16.9544197Z     not ok 2 Error: Request failed with status code 400
2023-03-24T07:09:16.9548249Z       ---
2023-03-24T07:09:16.9551580Z         operator: error
2023-03-24T07:09:16.9555232Z         at: bound (/home/runner/work/cacti/cacti/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
2023-03-24T07:09:16.9556608Z         stack: |-
2023-03-24T07:09:16.9560490Z           Error: Request failed with status code 400
2023-03-24T07:09:16.9563523Z               at createError (/home/runner/work/cacti/cacti/node_modules/axios/lib/core/createError.js:16:15)
2023-03-24T07:09:16.9565808Z               at settle (/home/runner/work/cacti/cacti/node_modules/axios/lib/core/settle.js:17:12)
2023-03-24T07:09:16.9568165Z               at IncomingMessage.handleStreamEnd (/home/runner/work/cacti/cacti/node_modules/axios/lib/adapters/http.js:269:11)
2023-03-24T07:09:16.9571548Z               at IncomingMessage.emit (node:events:538:35)
2023-03-24T07:09:16.9573905Z               at IncomingMessage.emit (node:domain:475:12)
2023-03-24T07:09:16.9577172Z               at endReadableNT (node:internal/streams/readable:1345:12)
2023-03-24T07:09:16.9578688Z               at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-24T07:09:16.9601917Z       ...
2023-03-24T07:09:16.9720594Z     # AFTER runs tx on an Iroha v1.2.0 ledger
2023-03-24T07:09:16.9740099Z     Bail out! Error: Request failed with status code 400
2023-03-24T07:09:16.9898425Z Bail out! Error: Request failed with status code 400
```

**Logs/Stack traces**

[2023-03-24T05-33-32_cacti_test_crash_connector_iroha.log](https://github.com/hyperledger/cacti/files/11064590/2023-03-24T05-33-32_cacti_test_crash_connector_iroha.log)

**Comment by petermetz** [comment]
Closing due to the Iroha v1 connector having been deprecated/retired.
