### ISSUE TITLE
fix(vscode/devcontainer): unexpected exit stdout /etc/passwd

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2404]
**Describe the bug**

Sometimes the dev container fails to start (or it does start but crashes immediately - without any error)

**To Reproduce**

Not sure how to reproduce because I never could. People have been reporting it every now and then though.

**Expected behavior**

The dev container is a foundational peace to the contributor experience and so it should be quite stable.

**Logs/Stack traces**

TBD

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

`main` but also this has been an issue for many releases going back pre-1.0.0

**Additional context**

We have bigger plans to run the CI via the dev container as well and so a refactor of the image is necessary because of that as well (right now the image wouldn't work on the GitHub workflow CIs)

**Comment by petermetz** [comment]
I have a mostly working Dockerfile, the last issue with it is that an upgraded Fabric 2.x AIO image still cannot pass the tests because of this issue:

```sh
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2> [2023-05-03T22:59:40.725Z] ERROR (DeployContractEndpointV1): DeployContractEndpointV1#handleRequest() failed to serve contract deploy request Error: All configured authentication methods failed
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at doNextAuth (/workspaces/cacti/node_modules/ssh2/lib/client.js:803:21)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at tryNextAuth (/workspaces/cacti/node_modules/ssh2/lib/client.js:993:7)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at USERAUTH_FAILURE (/workspaces/cacti/node_modules/ssh2/lib/client.js:373:11)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at 51 (/workspaces/cacti/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Protocol.onPayload (/workspaces/cacti/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at AESGCMDecipherNative.decrypt (/workspaces/cacti/node_modules/ssh2/lib/protocol/crypto.js:987:26)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Protocol.parsePacket [as _parse] (/workspaces/cacti/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Protocol.parse (/workspaces/cacti/node_modules/ssh2/lib/protocol/Protocol.js:293:16)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Socket.<anonymous> (/workspaces/cacti/node_modules/ssh2/lib/client.js:713:21)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Socket.emit (node:events:513:28)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Socket.emit (node:domain:489:12)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at addChunk (node:internal/streams/readable:315:12)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at readableAddChunk (node:internal/streams/readable:289:9)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at Socket.Readable.push (node:internal/streams/readable:228:10)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2>   level: 'client-authentication'
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 2> }
 FAIL  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts 1 failed of 3 2m
 ✖ Error: Request failed with status code 500


```
