### ISSUE TITLE
fix(ci): DeprecationWarning in yarn_custom_checks

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2956]
**Describe the bug**

There are several DeprecationWarning in weaver packages in `yarn_custom_checks` CI tests. There are few warnings in `cactus-example-carbon-accounting-frontend` but they are triggered by dependent packages, so I don't think we can fix them.

``` bash
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/sdks/fabric/interoperation-node-sdk/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/sdks/besu/node/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/core/drivers/fabric-driver/node_modules/@hyperledger/cacti-weaver-sdk-fabric/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/samples/fabric/fabric-cli/node_modules/@hyperledger/cacti-weaver-sdk-fabric/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/samples/besu/besu-cli/node_modules/@hyperledger/cacti-weaver-sdk-besu/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/examples/cactus-example-carbon-accounting-frontend/node_modules/@ionic-native/splash-screen/package.json' of 'bundle.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/examples/cactus-example-carbon-accounting-frontend/node_modules/@ionic-native/status-bar/package.json' of 'bundle.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/examples/cactus-example-supply-chain-frontend/node_modules/@ionic-native/splash-screen/package.json' of 'bundle.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/examples/cactus-example-supply-chain-frontend/node_modules/@ionic-native/status-bar/package.json' of 'bundle.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
(node:2714) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/runner/work/cacti/cacti/weaver/core/identity-management/iin-agent/node_modules/@hyperledger/cacti-weaver-sdk-fabric/package.json' of 'build/index.js'. Please either fix that or report it to the module author
    at tryPackage (node:internal/modules/cjs/loader:449:15)
    at Function.Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/runner/work/cacti/cacti/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/work/cacti/cacti/node_modules/resolve-from/index.js:46:47)
    at _default (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/module-root.js:18:54)
    at loadModuleData (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/utils/index.js:40:61)
    at discoverPropertyDep (/home/runner/work/cacti/cacti/node_modules/depcheck/dist/check.js:106:33)
```

**To Reproduce**

See https://github.com/hyperledger/cacti/actions/workflows/ci.yaml  / yarn_custom_checks for current status.

**Expected behavior**

Most warnings should be fixed

**Comment by aldousalvarez** [comment]
Hello @jagpreetsinghsasan I would like to work on this one. Thank you
