### ISSUE TITLE
Build failed : Supply-chain-app

### ISSUE THREAD

**Issue by ak1334** [hyperledger/cacti#2969]
**Describe the bug**
Supply chain app front-end is failing to run. When I run "yarn start:example-supply-chain", it fails and gives error as "Unknown Syntax Error: Unsupported option name ("--no-lockfile")."

**To Reproduce**
1. `npm run enable-corepack`
2. `npm run configure`
3. `yarn start:example-supply-chain`
After the third command it gives mentioned error.

**Expected behavior**
Supply chain app should run and load in the browser and able to perform all the transactions.

**Logs/Stack traces**
Unknown Syntax Error: Unsupported option name ("--no-lockfile").

**Screenshots**

**Operating system name, version, build:**
Linux 5.15.0-88-generic x86_64
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

**Hyperledger Cactus Plugins/Connectors Used**
> Besu, Fbaric and corda

**Additional context**
@petermetz , could you please check this.

**Comment by outSH** [comment]
@ak1334 What version of yarn do you use? We've migrated to 3.X some time ago.

To check: `yarn -v`
To install 3.X: `npm run enable-corepack`

**Comment by ak1334** [comment]
@outSH , yarn version Im using is : 3.6.0

**Comment by outSH** [comment]
OK, there is no `--no-lockfile` flag in yarn 3 and that's what's causing the problem (sorry, I though we'd have caught error like that by now, so long after upgrade). 

To run the app you can run the following command instead (from root of the project, may take some time):
`yarn build:dev && cd ./examples/supply-chain-app/ && touch yarn.lock; yarn install && yarn start`
And to cleanup (after your'e done):
`rm -rf ./examples/supply-chain-app/.yarn; rm -rf ./examples/supply-chain-app/yarn.lock`

**Comment by outSH** [comment]
There's another problem in command status check in fabric connector `deployContractGoSourceV1` method:

``` bash
[2024-01-11T13:21:59.695Z] DEBUG (PluginLedgerConnectorFabric): Copy to CLI Container CMD Response: { code: 0, signal: null, stdout: '', stderr: '' }
[2024-01-11T13:21:59.698Z] ERROR (SupplyChainAppDummyInfrastructure): Deployment of smart contracts crashed:  CodedError: "copyToCliRes.code === null" is falsy, need a truthy value.
    at Checks.truthy (/home/vagrant/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-common/dist/lib/main/typescript/checks.js:16:19)
    at PluginLedgerConnectorFabric.deployContractGoSourceV1 (/home/vagrant/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:458:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupplyChainAppDummyInfrastructure.deployContracts (/home/vagrant/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.js:215:29)
    at async SupplyChainApp.start (/home/vagrant/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app.js:124:31)
    at async launchApp (/home/vagrant/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app-cli.js:18:9) {
  code: '-1'
}
```

**Comment by ak1334** [comment]
@outSH , thanks for helping out. I'm getting same error as you mentioned.  
![build_error](https://github.com/hyperledger/cacti/assets/7413389/594f7c0e-0729-406e-b7bb-00ecfc7a0b89)

Error log : 

Copy to CLI Container CMD: /usr/local/bin/docker cp /opt/gopath/src/shipment/shipment.go cli:/opt/gopath/src/shipment/shipment.go
[2024-01-11T18:41:30.166Z] DEBUG (PluginLedgerConnectorFabric): Copy to CLI Container CMD Response: { code: 0, signal: null, stdout: '', stderr: '' }
[2024-01-11T18:41:30.168Z] ERROR (SupplyChainAppDummyInfrastructure): Deployment of smart contracts crashed:  CodedError: "copyToCliRes.code === null" is falsy, need a truthy value.
    at Checks.truthy (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-common/dist/lib/main/typescript/checks.js:16:19)
    at PluginLedgerConnectorFabric.deployContractGoSourceV1 (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:458:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupplyChainAppDummyInfrastructure.deployContracts (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.js:215:29)
    at async SupplyChainApp.start (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app.js:124:31)
    at async launchApp (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app-cli.js:18:9) {
  code: '-1'
}
SupplyChainApp crashed. Existing... CodedError: "copyToCliRes.code === null" is falsy, need a truthy value.
    at Checks.truthy (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-common/dist/lib/main/typescript/checks.js:16:19)
    at PluginLedgerConnectorFabric.deployContractGoSourceV1 (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:458:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupplyChainAppDummyInfrastructure.deployContracts (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/infrastructure/supply-chain-app-dummy-infrastructure.js:215:29)
    at async SupplyChainApp.start (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app.js:124:31)
    at async launchApp (/home/akshay.karale_sna@npci.org.in/Desktop/cacti-main9/cactus/examples/supply-chain-app/node_modules/@hyperledger/cactus-example-supply-chain-backend/dist/lib/main/typescript/supply-chain-app-cli.js:18:9) {
  code: '-1'
}
[2024-01-11T18:41:30.169Z] INFO (SupplyChainAppDummyInfrastructure): Stopping...

is there any way we cam fix this?
@outSH 
@petermetz 
@VRamakrishna

**Comment by outSH** [comment]
@ak1334 Sorry for late response, I think PR #2983 should solve the issue (thank you @aldousalvarez!), please retest and let us know if there are any problems remaining :)

**Comment by ak1334** [comment]
Hi @outSH , I have tested with the mentioned steps , I have got the JWT as well :  
![Screenshot from 2024-02-01 01-47-58](https://github.com/hyperledger/cacti/assets/7413389/142c60bf-79f0-44f3-91b4-57365f52bca2)

But when I try to click Bamboo Harvests, nothings happens as the dialogue box opens up but it does not create the entry, 
ref. below SS
![bamboo_harvests](https://github.com/hyperledger/cacti/assets/7413389/b7543a47-df5c-4f73-9b5a-f2fa9fb2100f)

**Comment by outSH** [comment]
@ak1334 It is working on my machine now:

![image](https://github.com/hyperledger/cacti/assets/9387513/2f775b48-cc1d-4954-bacb-1aed1abd8ed2)

One problem that I've noticed though is that sometimes you need to click `+` button couple of times in order for pop-up to appear :S It seem Angular related issue but I don't know either angular or that app to well to diagnose it completely, sorry. Please try running everything from a fresh state, maybe this will help.

Also, if the problem persist, please share logs from the backend and from browser console, maybe someone else will have a better idea

**Comment by petermetz** [comment]
> is there any way we cam fix this? @outSH @petermetz @VRamakrishna

@ak1334 Sorry for the slow response! For the short term it's like @outSH said above and for the longer term what I've been working on is migrating the supply chain example onto Fabric v2 which is much more stable than the older v1 version. So please stay tuned for that as well!

**Comment by ak1334** [comment]
Thank you @petermetz , for response. As I followed the steps mentioned by @outSH , the app is working fine now. But still the behavior is unpredictable, some times it fails. I will wait for the stable release as you mentioned.

**Comment by petermetz** [comment]
@ak1334 Circling back on this in case you are still having issues: It should be pretty stable by now, but if not, please re-open the issue. We want to make sure that people are not hindered by problems like this.
