### ISSUE TITLE
deploy-lock-asset test for fabric connector fails

### ISSUE THREAD

**Issue by dgmurx** [hyperledger/cacti#3261]
**Describe the bug**

The `deploy-lock-asset.test.ts` test for the `cactus-plugin-ledger-connector-fabric` fails during `enrollAdminV2()`. It tries to contact the CA server but fails with error `ECONNREFUSED`.

**To Reproduce**

- Start VS Code and open the cacti repository using the devcontainer
- Copy `.vscode/template.launch.json` to `.vscode/launch.json`
- Open `packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts`
- Run `TAP: Current TS Test File` from the "debug and run" window.

**Expected behavior**

The test passes.

**Logs/Stack traces**

```sh
vscode ➜ /workspaces/cacti (main) $  cd /workspaces/cacti ; /usr/bin/env TS_NODE_PROJECT=tsconfig.json 'NODE_OPTIONS= --require /vscode/vscode-server/bin/linux-x64/b58957e67ee1e712cebf466b995adf4c5307b2bd/extensions/ms-vscode.js-debug/src/bootloader.js  --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS=:::{"inspectorIpc":"/tmp/node-cdp.768-7b7a8999-7.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/local/share/nvm/versions/node/v18.19.0/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","mandatePortTracking":true,"fileCallback":"/tmp/node-debug-callback-421a37b5108468be"}' /usr/local/share/nvm/versions/node/v18.19.0/bin/node -r ts-node/register packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts 
Debugger attached.
TAP version 13
# BEFORE deploys Fabric 2.x contract from typescript source
ok 1 Pruning didn't throw OK
# deploys Fabric 2.x contract from typescript source
ok 2 getConnectionProfileOrg1() out truthy OK
[2024-05-14T08:57:20.145Z] ERROR (FabricTestLedgerV1): FabricTestLedgerV1#enrollAdminV2() Failure: Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:7054]
    at ClientRequest.<anonymous> (/workspaces/cacti/packages/cactus-test-tooling/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (node:events:517:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 7054
}
[2024-05-14T08:57:20.168Z] ERROR (FabricTestLedgerV1): FabricTestLedgerV1#enrollAdmin() Failure: r [RuntimeError]: FabricTestLedgerV1#enrollAdminV2() Exception:
    at FabricTestLedgerV1.enrollAdminV2 (/workspaces/cacti/packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts:360:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FabricTestLedgerV1.enrollAdmin (/workspaces/cacti/packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts:367:19)
    at async /workspaces/cacti/packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts:89:26 {
  cause: Error: Calling enroll endpoint failed with error [Error: connect ECONNREFUSED ::1:7054]
      at ClientRequest.<anonymous> (/workspaces/cacti/packages/cactus-test-tooling/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
      at ClientRequest.emit (node:events:517:28)
      at ClientRequest.emit (node:domain:489:12)
      at TLSSocket.socketErrorListener (node:_http_client:501:9)
      at TLSSocket.emit (node:events:517:28)
      at TLSSocket.emit (node:domain:489:12)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
    errno: -111,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 7054
  }
}
not ok 3 RuntimeError: FabricTestLedgerV1#enrollAdmin() Exception:
  ---
    operator: error
    at: bound call (/workspaces/cacti/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
    stack: |-
      RuntimeError: FabricTestLedgerV1#enrollAdmin() Exception:
          at FabricTestLedgerV1.enrollAdmin (/workspaces/cacti/packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts:371:13)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async /workspaces/cacti/packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-lock-asset.test.ts:89:26
  ...
[2024-05-14T08:57:20.255Z] INFO (containers#log-diagnostics): ContainerDiagnostics='{\n' +
  '    "images": [\n' +
  '        {\n' +
  '            "Containers": -1,\n' +
  '            "Created": 1715005721,\n' +
  '            "Id": "sha256:648c96bd104cc394816f1b2bb241eaef651117be2f58a2087fa3cf9550eade01",\n' +
  '            "Labels": {\n' +
  '                "dev.containers.id": "base-alpine",\n' +
  '                "dev.containers.release": "v0.3.34",\n' +
  '                "dev.containers.source": "https://github.com/devcontainers/images",\n' +
  '                "dev.containers.timestamp": "Wed, 03 Apr 2024 16:34:11 GMT",\n' +
  '                "dev.containers.variant": "3.16",\n' +
  '                "devcontainer.metadata": "[ {\\"id\\":\\"./local-features/git\\"}, {\\"id\\":\\"ghcr.io/devcontainers/features/common-utils:2\\"}, {\\"remoteUser\\":\\"vscode\\"} ]",\n' +
  '                "version": "0.208.3"\n' +
  '            },\n' +
  '            "ParentId": "",\n' +
  '            "RepoDigests": [],\n' +
  '            "RepoTags": [\n' +
  '                "vsc-volume-bootstrap:latest"\n' +
  '            ],\n' +
  '            "SharedSize": -1,\n' +
  '            "Size": 789456234\n' +
  '        },\n' +
  '        {\n' +
  '            "Containers": -1,\n' +
  '            "Created": 1714490708,\n' +
  '            "Id": "sha256:0f2c532dff08bd9389e0d06d21392d927e1c47cfea317dd68e0aee615ac42ceb",\n' +
  '            "Labels": {\n' +
  '                "dev.containers.features": "common",\n' +
  '                "dev.containers.id": "base-ubuntu",\n' +
  '                "dev.containers.release": "v0.3.34",\n' +
  '                "dev.containers.source": "https://github.com/devcontainers/images",\n' +
  '                "dev.containers.timestamp": "Wed, 03 Apr 2024 16:34:34 GMT",\n' +
  '                "dev.containers.variant": "jammy",\n' +
  '                "devcontainer.metadata": "[ {\\"id\\":\\"ghcr.io/devcontainers/features/common-utils:2\\"}, {\\"id\\":\\"ghcr.io/devcontainers/features/git:1\\"}, {\\"remoteUser\\":\\"vscode\\"}, {\\"id\\":\\"ghcr.io/devcontainers-contrib/features/curl-apt-get:1\\"}, {\\"id\\":\\"ghcr.io/devcontainers-contrib/features/protoc:1\\"}, {\\"id\\":\\"ghcr.io/devcontainers/features/docker-outside-of-docker:1\\",\\"entrypoint\\":\\"/usr/local/share/docker-init.sh\\",\\"mounts\\":[{\\"source\\":\\"/var/run/docker.sock\\",\\"target\\":\\"/var/run/docker-host.sock\\",\\"type\\":\\"bind\\"}],\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"ms-azuretools.vscode-docker\\"]}}}, {\\"id\\":\\"ghcr.io/devcontainers/features/git:1\\"}, {\\"id\\":\\"ghcr.io/devcontainers/features/go:1\\",\\"init\\":true,\\"capAdd\\":[\\"SYS_PTRACE\\"],\\"securityOpt\\":[\\"seccomp=unconfined\\"],\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"golang.Go\\"]}}}, {\\"id\\":\\"ghcr.io/devcontainers/features/java:1\\",\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"vscjava.vscode-java-pack\\"],\\"settings\\":{\\"java.import.gradle.java.home\\":\\"/usr/local/sdkman/candidates/java/current\\"}}}}, {\\"id\\":\\"ghcr.io/devcontainers/features/node:1\\",\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"dbaeumer.vscode-eslint\\"]}}}, {\\"id\\":\\"ghcr.io/devcontainers/features/rust:1\\",\\"capAdd\\":[\\"SYS_PTRACE\\"],\\"securityOpt\\":[\\"seccomp=unconfined\\"],\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"vadimcn.vscode-lldb\\",\\"rust-lang.rust-analyzer\\",\\"tamasfe.even-better-toml\\",\\"serayuzgur.crates\\"],\\"settings\\":{\\"files.watcherExclude\\":{\\"**/target/**\\":true}}}}}, {\\"id\\":\\"ghcr.io/dhoeric/features/trivy:1.0.0\\"}, {\\"postCreateCommand\\":\\"echo \\\\\\"source /usr/share/bash-completion/completions/git\\\\\\" >> ~/.bashrc\\",\\"customizations\\":{\\"vscode\\":{\\"extensions\\":[\\"bierner.markdown-mermaid\\",\\"mhutchie.git-graph\\",\\"alefragnani.bookmarks\\",\\"yzhang.markdown-all-in-one\\",\\"trabpukcip.vscode-npm-scripts\\",\\"jebbs.plantuml\\",\\"ms-vscode-remote.vscode-remote-extensionpack\\",\\"juanblanco.solidity\\",\\"dbaeumer.vscode-eslint\\",\\"42crunch.vscode-openapi\\",\\"esbenp.prettier-vscode\\",\\"eamodio.gitlens\\",\\"streetsidesoftware.code-spell-checker\\",\\"github.vscode-pull-request-github\\",\\"codeandstuff.package-json-upgrade\\"]}}} ]",\n' +
  '                "org.opencontainers.image.ref.name": "ubuntu",\n' +
  '                "org.opencontainers.image.version": "22.04",\n' +
  '                "version": "1.0.23"\n' +
  '            },\n' +
  '            "ParentId": "",\n' +
  '            "RepoDigests": [],\n' +
  '            "RepoTags": [\n' +
  '                "vsc-cacti-861dd587320ec5bc2db569be98318c5887cf19a71ac627bc8fb608a0a974b1c9-features:latest"\n' +
  '            ],\n' +
  '            "SharedSize": -1,\n' +
  '            "Size": 4680437042\n' +
  '        },\n' +
  '        {\n' +
  '            "Containers": -1,\n' +
  '            "Created": 1713203243,\n' +
  '            "Id": "sha256:9587b721df36303a53a8a2e67b5824962602dcaf6d239598530d327bce08d1db",\n' +
  '            "Labels": {\n' +
  '                "org.opencontainers.image.created": "2024-04-15T17:29:27.887Z",\n' +
  '                "org.opencontainers.image.description": "Hyperledger Fabric is an enterprise-grade permissioned distributed ledger framework for developing solutions and applications. Its modular and versatile design satisfies a broad range of industry use cases. It offers a unique approach to consensus that enables performance at scale while preserving privacy.",\n' +
  '                "org.opencontainers.image.licenses": "Apache-2.0",\n' +
  '                "org.opencontainers.image.ref.name": "ubuntu",\n' +
  '                "org.opencontainers.image.revision": "5efcea7216c8d316fa3d4a32e008ba22f1757a44",\n' +
  '                "org.opencontainers.image.source": "https://github.com/hyperledger/fabric",\n' +
  '                "org.opencontainers.image.title": "fabric",\n' +
  '                "org.opencontainers.image.url": "https://github.com/hyperledger/fabric",\n' +
  '                "org.opencontainers.image.version": "2.5.7"\n' +
  '            },\n' +
  '            "ParentId": "",\n' +
  '            "RepoDigests": [\n' +
  '                "hyperledger/fabric-tools@sha256:26b0474b92d7d1ecfd259ef62783a5ccec687e1f8793e1ce293e3290345f4b54"\n' +
  '            ],\n' +
  '            "RepoTags": [\n' +
  '                "hyperledger/fabric-tools:2.5",\n' +
  '                "hyperledger/fabric-tools:2.5.7",\n' +
  '                "hyperledger/fabric-tools:latest"\n' +
  '            ],\n' +
  '            "SharedSize": -1,\n' +
  '            "Size": 546359255\n' +
  '        },\n' +
  '        {\n' +
  '            "Containers": -1,\n' +
  '            "Created": 1713203044,\n' +
  '            "Id": "sha256:4b70009a7773f3be35274e4ffe148e182e4c8465cad66dd54775abdc01cd171b",\n' +
  '            "Labels": {\n' +
  '                "org.opencontainers.image.created": "2024-04-15T17:29:05.770Z",\n' +
  '                "org.opencontainers.image.description": "Hyperledger Fabric is an enterprise-grade permissioned distributed ledger framework for developing solutions and applications. Its modular and versatile design satisfies a broad range of industry use cases. It offers a unique approach to consensus that enables performance at scale while preserving privacy.",\n' +
  '                "org.opencontainers.image.licenses": "Apache-2.0",\n' +
  '                "org.opencontainers.image.ref.name": "ubuntu",\n' +
  '                "org.opencontainers.image.revision": "5efcea7216c8d316fa3d4a32e008ba22f1757a44",\n' +
  '           '... 79743 more characters

1..3
# tests 3
# pass  2
# fail  1

Waiting for the debugger to disconnect...
```

(I removed some of the output from the `ContainerDiagnostics` at the end -- most of it is trimmed anyways. If you believe it might be relevant, please let me know.)

**Screenshots**

--

**Cloud provider or hardware configuration:**

I am running the software on a laptop computer.

**Operating system name, version, build:**

The host OS is Windows 10. I ran the tests via VS Code on the devcontainer:
```sh
vscode ➜ /workspaces/cacti (main) $ printf "$(uname -srm)\n$(cat /etc/os-release)\n"
Linux 5.15.133.1-microsoft-standard-WSL2 x86_64
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Hyperledger Cactus release version or commit (git rev-parse --short HEAD):**

Commit `7e55ac431`.

**Hyperledger Cactus Plugins/Connectors Used**

 - Fabric

**Additional context**

--

**Comment by petermetz** [comment]
@dgmurx Thank you for the detailed report this helps narrow it down for sure! I am unable to reproduce it on a PopOS machine, but your logs offer some clues by showing that it's trying to connect to localhost through IPv6 instead of IPv4 which have been causing trouble with our tests in other scenarios due to NodeJS v18 defaulting to IPv6 but not really supporting it (or something else in the stack not supporting it I'm not sure which one TBH).

The bottom line is though, most likely somewhere in the config there is a declaration of `localhost` instead of an explicit `127.0.0.1` and in your environment (WSL) this probably doesn't work the way it does for me on PopOS (a Debian family distro)

The fix would be to locate this instance of `localhost` mentioned above, but it's hard for me to figure it out without being able to reproduce the issue.

https://wiki.hyperledger.org/display/cactus/Daily+Pair+Programming+Calls

---

Now onto actionable advice on how to try and fix it. Some ideas:
1. Try to research if WSL has IPv6 issues.
2. Try to research if IPv6 is disabled and if you could enable it and if that would fix the problem

Either way, let me know how it goes!

**Comment by dgmurx** [comment]
Thanks for the quick reply! You are right, IPv6 is the problem. I could make the tests pass by making two changes to
`fabric-test-ledger-v1.ts`. The error I mentioned above was fixed by changing the url for the CAs in the function `getConnectionProfileOrgX`: 
https://github.com/hyperledger/cacti/blob/f932da8352aea255cfd45cbce68a42106ca1357f/packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts#L544 
to `` cas[caName].url = `https://127.0.0.1:${caHostPort}` ``.

This lead to a new `ECONNREFUSED` error popping up, when trying to contact `::1:30022`. I could get around it by changing the sshConfig in `getSshConfig`
https://github.com/hyperledger/cacti/blob/f932da8352aea255cfd45cbce68a42106ca1357f/packages/cactus-test-tooling/src/main/typescript/fabric/fabric-test-ledger-v1.ts#L1263-L1268
to read `host: "127.0.0.1"`.

From what I read, IPv6 support for WSL can be enabled through [a setting that changes its networking architecture](https://learn.microsoft.com/en-us/windows/wsl/networking#mirrored-mode-networking), but this setting is available only for Windows 11 and I am on 10, so I can't test it.

What does work is to use cacti directly from a WSL distro, ie without the devcontainer, which is fine for me.

**Comment by petermetz** [comment]
> What does work is to use cacti directly from a WSL distro, ie without the devcontainer, which is fine for me.

@dgmurx Alright, that's good enough for me that we can close this for now because there is a fix (Win 11) and a workaround (no use vanilla WSL2 on Win 10).

Thank you for the investigation into this. It always helps to have these data points established later on for others who will run into the same problem.

**Comment by dgmurx** [comment]
Thank you, too, for the help!
